export const LOADBANNERDATA = 'home/recommend/loadbannerdata'
export const LOADTRAVALDATA = 'home/recommend/loadtravldata'
export const LOADQUESTIONDATA = 'home/recommend/loadquestiondata'
export const LOADSPECIALDATA = 'home/recommend/loadspecialdata'
export const CHANGETRAVALLISTSTATE = 'home/recommend/changetravalliststate'